apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: database
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: d29yZHByZXNz
  MYSQL_PASSWORD: d29yZHByZXNz
  MYSQL_ROOT_PASSWORD: d29yZHByZXNz