apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: database
spec:
  type: ClusterIP
  ports:
  - port: 3306  # this port has to be 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb